FROM node:22-slim

WORKDIR /app

# Install OpenSSL for Prisma
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y openssl && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 3333
CMD ["npm", "run", "dev"]
