service: draftmark

image: draftmark-app/draftmark

servers:
  web:
    - 46.62.150.50

proxy:
  ssl: true
  host: draftmark.app
  app_port: 3000
  healthcheck_path: /up

registry:
  server: ghcr.io
  username: facundofarias
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - DATABASE_URL

ssh:
  keys: ["~/.ssh/id_ed25519"]
  keys_only: true

builder:
  arch: amd64

accessories:
  db:
    image: postgres:17-alpine
    host: 46.62.150.50
    port: "127.0.0.1:5436:5432"
    env:
      clear:
        POSTGRES_USER: draftmark
        POSTGRES_DB: draftmark_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
